version: '3.8'
services:
  mysql:
    image: mysql:5
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    environment:
      MYSQL_DATABASE: sample_development
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
